### ISSUE TITLE
I want to make sure the following explanations is true

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#102]
"The order amount that needs to be reached before payment option becomes available in checkout.
Set to 0 or leave empty to disable."

"The order amount can't exceed this amount. If order amount goes above the entered amount the payment option becomes unavailable.
Set to 0 or leave empty to disable."
![skarmavbild 2015-05-09 kl 10 12 20](https://cloud.githubusercontent.com/assets/4968755/7549427/eb015f4e-f633-11e4-95a9-22c07e61102e.png)

**Comment by andyjohansson** [comment]
Is this fixed @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Yes it should be
