### ISSUE TITLE
Remove payment action for bank

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#104]
Also remove the code for this regarding the transaction so that bank payments cannot be auto activated.

**Comment by Boxedsolutions** [comment]
I can see if we can hide it. It needs to be that element or the initialize wont run which set pending_payment Status

**Comment by andyjohansson** [comment]
It should be able to be hidden, saw that in the documentation.

**Comment by andyjohansson** [comment]
Why can't we hide the whole setting, just looks weird now? I sat it down in the bottom now but there must be a way to hide the whole thing?

**Comment by Boxedsolutions** [comment]
Its fully hidden now :)
