### ISSUE TITLE
Translation is missing for Get Address

### ISSUE THREAD

**Issue by svenakela** [Billmate/magento#106]
The Get Address feature is not translating into Swedish because the translation keys are missing.
Billmate_invoice.csv:
    "Person Number","Org/Personnummer"
Billmate_Common.csv:
    "Get Address", "Hämta adress"

Please note that the translation is Case Sensitive.

**Comment by Boxedsolutions** [comment]
What a miss of me to miss this words. Will fix for the next release and move the person_number to Billmate_common to, because of its a common field.
