### ISSUE TITLE
Remove style tags from Get Address feature

### ISSUE THREAD

**Issue by svenakela** [Billmate/magento#107]
Will only mess up the address form and they should be in CSS.
With the style attributes removed the Get Address feature works without problem, the only difference is the button being below and not behind the number field.

**Comment by Boxedsolutions** [comment]
Will move it to billmatestyle.css with a comment above to clearify that it is the get address elements. It makes more sense to have the css in a file than on the elements, in case someone wants to use a own styling with the feature use custom css.
