### ISSUE TITLE
Invoice fee not visible in payment choices

### ISSUE THREAD

**Issue by svenakela** [Billmate/magento#108]
When a customer is going to choose a payment option there is no information text about additional fees for billing. The fee configured in Admin should be visible for the customer.

**Comment by andyjohansson** [comment]
Hi, you can set this in the title by yourself of the payment option. Or would you prefer if the module did this by default?

**Comment by andyjohansson** [comment]
We maybe should solve this like we have made on Prestashop @Boxedsolutions?

**Comment by svenakela** [comment]
The other payment and shipment modules we are using have a description text visible either directly under the choice or it becomes visible when the customer clicks on the radio button. In this text (or after) the invoice (or freight) fee is printed out automatically. 
Right now we've set this in the title bar of the payment option, I don't prefer such a solution as it is manual and easy to miss and it messes up a clean checkout interface. Automatically printing out the invoice fee if there is one is visually clean and user friendly.

**Comment by andyjohansson** [comment]
We will implement this in the next version @svenakela. Thanks for the feedback.

**Comment by svenakela** [comment]
Thumbs up!

**Comment by Boxedsolutions** [comment]
Should work now on magento-api-2-0

**Comment by andyjohansson** [comment]
@svenakela I'm about to push to master and release a new version. This should be resolved in the new release.

**Comment by andyjohansson** [comment]
Some issues still, see DM.

**Comment by andyjohansson** [comment]
Now it looks good.
