### ISSUE TITLE
Redirect Customer to FireCheckout Page on Browser BACK Button

### ISSUE THREAD

**Issue by magejunkie** [Billmate/magento#109]
So, if a customer goes to the Billmate payment page and press the BACK button on the browser, they get redirected to the Empty Shopping cart.

Can we keep the cart items intact and redirect them to the FireCheckout page instead of Empty Cart?

**Comment by andyjohansson** [comment]
Could you check this one out @Boxedsolutions?

**Comment by magejunkie** [comment]
Hi Jesper,

Any update on this one? Let me know if I can help you on this.

**Comment by andyjohansson** [comment]
Hi @magejunkie, I right now know that @Boxedsolutions is out on a business trip. If you would like to and know how to resolve this you can submit a pull request.

**Comment by Boxedsolutions** [comment]
Will think about this in this weekend, but i Wonder if it really are the best way to implement in the payment module?

I mean if the customer press cancel to abort the payment the cart contents is still there, but if he hits the back button, he is coming to the firecheckout, but as the order is placed when the customer checks out the session is cleared.

One possibility would be to set the qoute contents in the controller_action_predispatch_firecheckout_index_index observer if $session->getLastQuoteId() but you will need to check if cart has contents before so they not are doubled.

@andyjohansson @magejunkie

**Comment by magejunkie** [comment]
Hi Jesper,

Well, you can check how PayPal works. If we click the BACK BUTTON on the browser, the content of the cart are still there.

Let me know what solution you are thinking of @Boxedsolutions @andyjohansson

**Comment by andyjohansson** [comment]
This will be fixed on the back-end since we have come up with a solution to this there. Will be implemented soon. Will leave this issue open meantime @magejunkie.

**Comment by magejunkie** [comment]
Any idea when this will be fixed? How long we will have to wait? @andyjohansson

**Comment by magejunkie** [comment]
Hi @andyjohansson @Boxedsolutions Any idea when this improvement will be published?

**Comment by Boxedsolutions** [comment]
Working on a solution for this one. Should be fixed.
