### ISSUE TITLE
Include a special CSS file if it exists

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#11]
In order to make some adjustments to our CSS with that theme we should add a function to include a billmate-special.css if it exists on the server. That way it's easy for everyone to modify the css for the Billmate and make adjustments if necessary.

**Comment by andyjohansson** [comment]
This one should be easy to add @Boxedsolutions? Is it possbile to add this to the 2.0 release?

**Comment by Boxedsolutions** [comment]
Yes its possible,

**Comment by andyjohansson** [comment]
Ok, great.

**Comment by andyjohansson** [comment]
Can you test this one @Boxedsolutions ? Can you add some documentation on where to include the special css file here and I will update the documentation.

**Comment by Boxedsolutions** [comment]
/skin/frontend/base/default/css/billmatestyle-custom.css

I added this comment in the configuration view:
Activate if you want to use a custom stylesheet, add a file in directory : /skin/frontend/base/default/css named billmatestyle-custom.css

**Comment by andyjohansson** [comment]
Thanks. Will update the documentation then.

**Comment by Boxedsolutions** [comment]
Fixed by activation in Billmate Common module

**Comment by andyjohansson** [comment]
Please test and verify this @joakim-combain.

**Comment by joakim-combain** [comment]
How do I test this? I activated it but not sure what is supposed to happen.

**Comment by Boxedsolutions** [comment]
just check the console 
![customstyle](https://cloud.githubusercontent.com/assets/8977650/6329665/c2a28006-bb72-11e4-90e0-3d89998ca6b8.png)

**Comment by joakim-combain** [comment]
Ok. It's there so it's fixed then. Closing this issue.
