### ISSUE TITLE
Order sum is not correct, store vs billmate (but they are).

### ISSUE THREAD

**Issue by svenakela** [Billmate/magento#118]
Order is registered, customer chooses "Billmate Faktura".
In Magento Admin, go into the order and then Invoice.
"Debit online", click Invoice and following error is showing up:
   The amounts don't match. Billmate Online 805 and Store 801. Activate manually in Billmate.
The Store value really is 805, Billmate Backend shows 805.

**Comment by Boxedsolutions** [comment]
There is 2 important Questions I need. What is the invoice fee and taxrate? Which Magento version do you run?
I thought I had fixed all versions to work with the fee. 
What version of plugin do you run?

**Comment by svenakela** [comment]
SEK 16:- excl VAT.
25 % VAT.
MGO 1.9.1.0.
Not the latest hotfixed release but almost.
Den 10 jun 2015 00:11 skrev "Jesper Johansson" <notifications@github.com>:

**Comment by Boxedsolutions** [comment]
Its strange that this version makes this. I will make a test on our Magento 1.9.1 store to verify if it somewere was introduced a bug.

**Comment by Boxedsolutions** [comment]
@svenakela could you check the database tables listed below for the fields in the paranteses?
It sounds like that the invoice fee taxamount is not saved correctly.
sales_flat_order (fee_amount, base_fee_amount, fee_tax_amount, base_fee_tax_amount, fee_amount_invoiced,base_fee_amount_invoiced,fee_amount_refunded,base_fee_amount_refunded)

sales_flat_invoice (fee_amount, base_fee_amount,fee_tax_amount,base_fee_tax_amount)

sales_flat_creditmemo (fee_amount,base_fee_amount,fee_tax_amount,base_fee_tax_amount)

sales_flat_quote_address(fee_amount,base_fee_amount,fee_tax_amount,base_fee_tax_amount)

**Comment by svenakela** [comment]
I think you are into something. Here are some extracts from the tables.

sales_flat_invoice:
+------------+-----------------+----------------+---------------------+
| fee_amount | base_fee_amount | fee_tax_amount | base_fee_tax_amount |
|    16.0000 |         16.0000 |           NULL |                NULL |
|    16.0000 |         16.0000 |           NULL |                NULL |
|     0.0000 |          0.0000 |           NULL |                NULL |
|    16.0000 |         16.0000 |           NULL |                NULL |
+------------+-----------------+----------------+---------------------+

sales_flat_creditmemo: Empty

sales_flat_quote_address:
+------------+-----------------+----------------+---------------------+
| fee_amount | base_fee_amount | fee_tax_amount | base_fee_tax_amount |
+------------+-----------------+----------------+---------------------+
|     0.0000 |          0.0000 |           NULL |                NULL |
|    16.0000 |         16.0000 |         4.0000 |              4.0000 |
|     0.0000 |          0.0000 |           NULL |                NULL |
|     0.0000 |          0.0000 |           NULL |                NULL |
|     0.0000 |          0.0000 |           NULL |                NULL |
|     0.0000 |          0.0000 |           NULL |                NULL |
+------------+-----------------+----------------+---------------------+




2015-06-11 11:05 GMT+02:00 Jesper Johansson <notifications@github.com>:

**Comment by Boxedsolutions** [comment]
What does the sales_flat_order table says? What does sales_flat_order_payment (additional_info) says?
What is the Tax configuration for the Store? The Calculation Settings, to get a failing testcase I think we need to use same settings. 



My store is configured: 
Catalog prices incl tax
Shipping prices incl tax

**Comment by svenakela** [comment]
Catalog and shipping excl tax, all prices in shop incl tax.
25 % VAT.

sales_flat_order_payment.additional_information on a failing invoice:
a:3:{s:19:"billmateinvoice_fee";d:20;s:23:"billmateinvoice_fee_tax";d:4;s:9:"invoiceid";s:7:"1000138";}

select grand_total, base_total_invoiced, total_invoiced, base_tax_amount,
tax_amount, fee_amount, fee_tax_amount from sales_flat_order where
entity_id = ____;
+-------------+---------------------+----------------+-----------------+------------+------------+----------------+
| grand_total | base_total_invoiced | total_invoiced | base_tax_amount |
tax_amount | fee_amount | fee_tax_amount |
+-------------+---------------------+----------------+-----------------+------------+------------+----------------+
|    805.0000 |            801.0000 |       801.0000 |        161.0000 |
161.0000 |    16.0000 |         4.0000 |
+-------------+---------------------+----------------+-----------------+------------+------------+----------------+

Grand Total is correct. 805 x 0.8 = 644. 644 + 161 = 805. Total invoiced
(801) is missing the invoice tax.




2015-06-11 11:50 GMT+02:00 Jesper Johansson <notifications@github.com>:

**Comment by Boxedsolutions** [comment]
I will try these settings and see if it encounters some errors. 

If you want to look for your self where the code is adding invoiceFee, it is in Billmate/BillmateInvoice/Model/Order/invoice/Total/Fee.php

You could probably remove the Version_compare in this row, then it will add TaxAmount from order table. 


	    if($order->getFeeTaxAmount() > 0 && version_compare(Mage::getVersion(),'1.9.0.0','<')){

**Comment by Boxedsolutions** [comment]
@svenakela Did it work?

**Comment by svenakela** [comment]
I haven't, but as the version is 1.9.1.0 it will not go into that code.

2015-06-16 23:14 GMT+02:00 Jesper Johansson <notifications@github.com>:

**Comment by Boxedsolutions** [comment]
Change it to:
 if($order->getFeeTaxAmount() > 0 ){

this should add the tax to the fee.

**Comment by svenakela** [comment]
Changed.


2015-06-16 23:20 GMT+02:00 Jesper Johansson <notifications@github.com>:
