### ISSUE TITLE
After updating the module, I see this error for Bank Payment method.

### ISSUE THREAD

**Issue by magejunkie** [Billmate/magento#125]
CODE: 20637
MESSAGE: Error code is not yet defined! Trustly: ERROR_DUPLICATE_MESSAGE_ID

**Comment by andyjohansson** [comment]
Hi, from what I can see you were using a test account that is our own internal. How did you find those credentials?

**Comment by andyjohansson** [comment]
In the latest release the eid & secret for our internal testaccount got pushed as well. @Boxedsolutions will fix this in a hotfix ASAP.
