### ISSUE TITLE
Add support for Magento 2.0

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#142]
https://magento.com/developers/magento2

**Comment by andyjohansson** [comment]
It will be released Q4 this year. So probably late November. We need to be ready on day 1!

**Comment by Mirandawoods** [comment]
If one person makes everything, you surely will be disappointed with each of your future webpage. Users prefer a easy navigation on web pages. You can start using PHP whenever the will arises. visit mage4u.com to find out more

**Comment by andyjohansson** [comment]
This is in a seperate repo now.
