### ISSUE TITLE
Multiple Order Emails sent - Urgent Fix Needed

### ISSUE THREAD

**Issue by magejunkie** [Billmate/magento#144]
We are experiencing a very weird issue where our customers are receiving multiple order emails. Sometimes upto 11 order emails are been sent out at once. This is triggering issues with our customers as they are thinking that they paid multiple times by mistake.

We have noted this to be happening with Billmate Card so far. We tested our checkout with out payment methods and all seems to work good except Billmate.

**Comment by Boxedsolutions** [comment]
Noted, please contact us at support[at]billmate.se
