### ISSUE TITLE
Callback order canceled

### ISSUE THREAD

**Issue by magejunkie** [Billmate/magento#147]
We are experiencing a very weird issue. Our order status in Magento shows are processing whereas when looking at comments history we see the following:

Nov 25, 2015 10:51:04 PM| Canceled | Customer Not Notified 
Order canceled by callback

Nov 25, 2015 10:52:10 PM| Processing | Customer Notified 
 
Nov 25, 2015 10:52:10 PM| Processing | Customer Not Notified 
Order processing completed
Billmate status: Created
Transaction ID: 115

We aren't able to invoice or ship the order. Please check this issue.

**Comment by Boxedsolutions** [comment]
Which module version do you have? I guess you are running Firecheckout?

**Comment by magejunkie** [comment]
Yes we have FireCheckout and the latest BillMate module

**Comment by Boxedsolutions** [comment]
Its possible that the customer first tried with bank/cardpayment for trying with another method later. 

It seems very odd this issue. 

Why cant you invoice or ship? Whats the error message?

**Comment by magejunkie** [comment]
Yes we see a order that was cancelled first so probably customer tried
something. But it says in the comments history that Order cancelled by user.

Whereas for the processing order I sent you the comments history.

**Comment by Boxedsolutions** [comment]
Yes if something went wrong with the payments, we must mark the order cancelled. Then if a customer do a new try to pay with another option it will create the processing state, 

We are testing this today to see if there are some issues with our demo sites. If it is we will fix it asap.

**Comment by magejunkie** [comment]
OK thanks. Keep me posted

**Comment by Boxedsolutions** [comment]
Have you cleared all cache when install our new module? We cant reproduce it, when a order is cancelled by payment gateway and a customer do a new order we get a new order.

**Comment by magejunkie** [comment]
Yes we have all cache disabled. Did u try with FireCheckout?

**Comment by Boxedsolutions** [comment]
Yes we have a demo store with firecheckout

**Comment by Boxedsolutions** [comment]
Should be implemented

**Comment by victorauren** [comment]
Creates a new order and the old is cancelled
Works fine
