### ISSUE TITLE
Update everwhere eFinance Nordic AB is named

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#15]
Update to the new company name Billmate AB.

**Comment by Boxedsolutions** [comment]
The places i Found is updated in commit 9f9fb67

**Comment by andyjohansson** [comment]
I made a search in the new updated one and found references in the following files the eFinance, please update accordingly when I get new links.
*billmateinvoice.xml 
*billmatepopup.js

**Comment by andyjohansson** [comment]
Resolved, closing.
