### ISSUE TITLE
Partpayment when Using other currency

### ISSUE THREAD

**Issue by victorauren** [Billmate/magento#156]
When setting Swedish currency as base currency, and I add another for example GBP. Set the currency rate to 13.5321. When I make an order, I change the currency to GBP and there is alot of issus. 
When informatione about partpayment is shown it gives a huge amount to pay every month. Se attached image1. 

Then I get swedish krona in the last checkaout, se attached image2 

And when I place the order I get a message that is saying that you can't use this payment method. Se attached image3. 

When checking logs (248616) there is a roundnig issue: "rounding": -8479282,

![1](https://cloud.githubusercontent.com/assets/14887835/12913919/ceb54eb4-cf21-11e5-9a57-ea8d20424728.PNG)
![2](https://cloud.githubusercontent.com/assets/14887835/12913918/ceb2bc3a-cf21-11e5-8e29-ad814eda8dcd.PNG)
![3](https://cloud.githubusercontent.com/assets/14887835/12913917/ceb3366a-cf21-11e5-864b-f4500fc79640.PNG)

**Comment by Boxedsolutions** [comment]
Please Check again. Its magento standard to show Your credit card will be charged for...

**Comment by victorauren** [comment]
It's still an issue with roundings
256951 - LogId

**Comment by victorauren** [comment]
![checkout](https://cloud.githubusercontent.com/assets/14887835/13084296/29767078-d4d9-11e5-91c3-b6c684c31892.png)

**Comment by Boxedsolutions** [comment]
Implemented a new fix for this

**Comment by victorauren** [comment]
Now it works fine. Only show partpayment when swedish currency is choosed

**Comment by victorauren** [comment]
And when the option disappears the first issue with roundings is solved. 
Closing issue
