### ISSUE TITLE
Calculate correct VAT when tax calculation price_excludes tax in Catalog

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#16]
Find a correct way to calculate vat to prevent no flag is sent when product price is with tax. 

The methods involved is Card/Bankpayment

**Comment by andyjohansson** [comment]
What's the status on this one @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
There is no flags in the new Api :) 

All prices is sent without tax. We have to verify that it works only.

**Comment by andyjohansson** [comment]
I will close this one, unnecessary to have this one open...
