### ISSUE TITLE
Add link to our Manual to our plugins

### ISSUE THREAD

**Issue by billmate-support** [Billmate/magento#163]
New feature - Add link to all manuals inside our plugins. A suggestion, if
it is possible, it would be nice if the selected language is not Swedish,
it will show the link to the english version.

**Comment by Boxedsolutions** [comment]
Do you want it in Module settings? 
What different structure is the english vs Swedish?

**Comment by andyjohansson** [comment]
Please fix this for 3.0.3 @Boxedsolutions 
https://billmate.se/plugins/manual/Installationsmanual_Magento_Billmate.pdf
https://billmate.se/plugins/manual/Installation_Manual_Magento_Billmate.pdf

**Comment by Boxedsolutions** [comment]
In general settings? 
@andyjohansson

**Comment by andyjohansson** [comment]
Yes

**Comment by Boxedsolutions** [comment]
Fixed
