### ISSUE TITLE
Order gets Cancelled in Magento

### ISSUE THREAD

**Issue by victorauren** [Billmate/magento#167]
When make an order and pay with card, everything seems right except that the order get the status cancelled in Magenot. In BO the order is created, and the logs shows the transaction is ok and the callback is ok.

**Comment by victorauren** [comment]
I will try to recreate this in teststores
@Boxedsolutions

**Comment by Boxedsolutions** [comment]
Should be fixed with the new logic.

**Comment by kalorifri** [comment]
Tested, still need fix.
