### ISSUE TITLE
Redirected to cart Issue when Card/bank payment success

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#17]
Fix by set Session LastSuccessQuoteId To prevent Redirect to Cart

**Comment by Boxedsolutions** [comment]
This should work now.

**Comment by andyjohansson** [comment]
Can you test this and verify @joakim-combain?

**Comment by andyjohansson** [comment]
Have you tested yet @joakim-combain ?

**Comment by joakim-combain** [comment]
This is fixed. You can close this issue.
