### ISSUE TITLE
If cart is empty, checkout window should not be loaded

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#178]

**Comment by Boxedsolutions** [comment]
Wonder if we just should not load it or if we should redirect. 
@andyjohansson

**Comment by andyjohansson** [comment]
Is this still a issue?

**Comment by andyjohansson** [comment]
@Boxedsolutions

**Comment by Boxedsolutions** [comment]
It is fixed. Checkout will not be loaded with empty cart.
