### ISSUE TITLE
Thank you page looks weird

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#190]
<img width="1240" alt="skarmavbild 2017-03-20 kl 15 02 05" src="https://cloud.githubusercontent.com/assets/4968755/24103059/60bb6348-0d7e-11e7-84bf-26ed9c580a2b.png">

**Comment by Boxedsolutions** [comment]
Not plugin related
Dont think we could change from our plugin

**Comment by andyjohansson** [comment]
OK
