### ISSUE TITLE
Billmate 3.0.4 Rewrites Conflicts

### ISSUE THREAD

**Issue by urbancrew** [Billmate/magento#197]
Billmate_Common_Block_Checkout_Links,TM_FireCheckout_Block_Links
Billmate_Common_Block_Checkout_Cart_Sidebar,TM_FireCheckout_Block_Cart_Sidebar
Billmate_Common_Helper_Url,TM_FireCheckout_Helper_Url

**Comment by Boxedsolutions** [comment]
Yes those rewrite the same files. You will have to depend on TM_FireCheckout in app/etc/modules/Billmate_Common.xml
