### ISSUE TITLE
I got an error message while checking out with card.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#20]
Error code 9105: Article without tax is mandatory.

I used:

SNYGG GRUND TSHIRT KONFIGURERBAR
LITEN TESTPRODUKT ÅÄÖ
Discount code: Test åäö
Posten fixed

Grand total: 216.33

**Comment by Boxedsolutions** [comment]
Will fix soon. I think its a typo in discount row.

**Comment by Boxedsolutions** [comment]
Should be fixed now. Could you verify that.

**Comment by joakim-combain** [comment]
Yes, it's fixed.

**Comment by andyjohansson** [comment]
Great, closing the issue then.
