### ISSUE TITLE
Sending one additional product when ordering Snygg grund tshirt Konfigurerbar.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#21]
I've noticed that you are sending in an additional product when ordering Snygg grund tshirt Konfigurerbar. It's the color you are sending in as well. The problem is that you are sending it in with price and amount. I think you should be able to send it in with just the name of the product and nothing else.

It's not a big issue but it might be nice to fix so the invoice looks nice.

**Comment by joakim-combain** [comment]
We can pause this for now. Our programmer has to add functionality so we can send free text rows instead of entire articles. So when this is done you should send --freetext-- in article number. I'll let you know when it's fixed.

**Comment by Boxedsolutions** [comment]
I wonder if that really is necessary? I mean i Could get the simple article from the configurable product and append the title to the configurable product. And append the price if for examle a green t-shirt is more expensive than a regular. 

Will test that approach in the evening.

In magento a configurable products contains different simple_products. But --freetext-- could of course bee in use in some situations.

**Comment by joakim-combain** [comment]
Yeah, try that. I think we need to support it anyway and I think it's a good feature to have. Like you say, there could be scenarios that would require this.

**Comment by andyjohansson** [comment]
I agree with @Boxedsolutions. We can do it like that now but the added feature that @joakim-combain is suggesting is a great add to the API.

**Comment by joakim-combain** [comment]
It's not fixed, so if you add --freetext-- in article number, you should be able to send it in as just a free text row instead of an article. Use which ever method you want. :)

**Comment by andyjohansson** [comment]
What do you mean by not fixed?

**Comment by joakim-combain** [comment]
Have no idea why I wrote not fixed... Changed it now so now it says it's fixed instead. :)

**Comment by Boxedsolutions** [comment]
Should be fixed with commit 650a1bc083badf16f30042002d8c2e1912f7b717

**Comment by joakim-combain** [comment]
This is fixed. @andyjohansson you can close this issue.

**Comment by andyjohansson** [comment]
Closing then.
