### ISSUE TITLE
Sale setting doesn't work for card.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#22]
I changed card setting from authorized to sale, but it seems like you are sending in autoactivate=0. This should be 1 in case of Sale.

**Comment by Boxedsolutions** [comment]
Will look that up as soon as Possible

**Comment by Boxedsolutions** [comment]
Should be fixed in commit 19fce91f006b207e3b2fdf39d0661cabff47e2b5

**Comment by joakim-combain** [comment]
This issue is fixed. You can close it.
