### ISSUE TITLE
Translations needed in backend

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#23]
You need to translate Sale and Authorize only in Betalningsåtgärd. These should be Debitera direkt and Reservera belopp.

**Comment by Boxedsolutions** [comment]
Should be fixed in commit 19fce91f006b207e3b2fdf39d0661cabff47e2b5

**Comment by joakim-combain** [comment]
Fixed. @andyjohansson you can close this issue.

**Comment by andyjohansson** [comment]
Good.
