### ISSUE TITLE
All the address popups needs to be larger.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#24]
You need to increase the height of all the address popups. Right now the option to dismiss the popup to enter a new number or change payment method is outside the box. See screenshot: http://awesomescreenshot.com/05b469va9f

**Comment by Boxedsolutions** [comment]
Should be solved now.

**Comment by andyjohansson** [comment]
Will you test and verify?

**Comment by Boxedsolutions** [comment]
![billmatepopup](https://cloud.githubusercontent.com/assets/8977650/5746417/b918c32c-9c2f-11e4-965b-2056cdfb40e5.png)

**Comment by joakim-combain** [comment]
Fixed. You can close this issue.
