### ISSUE TITLE
Translation needed in part pay drop down menu.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#25]
It still says Month in the drop down menu when selecting how many months you want. See screenshot: https://drive.google.com/file/d/0B8nZhLflMVxNZ0VHdmN3Nm1GX3c/view?usp=sharing

**Comment by Boxedsolutions** [comment]
Should be fixed in commit 19fce91f006b207e3b2fdf39d0661cabff47e2b5

**Comment by joakim-combain** [comment]
This issue is fixed. @andyjohansson you can close this issue.

**Comment by andyjohansson** [comment]
Closing.
