### ISSUE TITLE
Translate needed for some error messages.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#26]
There seems to be an issue with some error messages showing in english instead of swedish. According to our developer it should be a plugin issue, he is always sending them in swedish if your BO account is in swedish, which it is. Here are screenshots of those I've found.

https://drive.google.com/file/d/0B8nZhLflMVxNNkJKNUFsOFFEUzg/view?usp=sharing (550101101 in invoice and part pay)
https://drive.google.com/file/d/0B8nZhLflMVxNVDB6OWxycWFOUkk/view?usp=sharing (5501011019 in invoice and part pay)

**Comment by Boxedsolutions** [comment]
Its the error messages from the new Api, a nice feature would be if its localized with the language sent to the api to get error messages in correct language.

**Comment by andyjohansson** [comment]
Do we have any API log id @joakim-combain  & @Boxedsolutions? So that we can investigate further.

**Comment by Boxedsolutions** [comment]
Should be fixed in latest commit 19fce91

**Comment by andyjohansson** [comment]
Ok, is it fixed in the testshop as well?

**Comment by Boxedsolutions** [comment]
Yes I allways update the testshop to verify.

**Comment by andyjohansson** [comment]
Ok, great.

**Comment by joakim-combain** [comment]
Fixed. @andyjohansson you can close this issue.

**Comment by andyjohansson** [comment]
Closing.
