### ISSUE TITLE
I got wrong values in a order, different values in BO and in Store.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#27]
I put an order and got different values in BO and in store. The item is the test product i added and I'm assuming it's because it has a special price if you buy at least 2 of them. Discount is the one that is wrong, that much I know. Check apilogsid 1314 and order id in store 100000031 and invoice number 6350 in BO.

**Comment by Boxedsolutions** [comment]
https://www.evernote.com/shard/s6/sh/ea7d47eb-264d-417f-af8b-ccbedd604f68/9c0c0a99608b0f39b60945662a5bd3fb Check this out. 

If i use the discount on articles with correct discount percent its not calculating SUM column down. I had to sum up all discounts and create a own total for this.

**Comment by joakim-combain** [comment]
Yeah, noticed now that we are having a bug here in the api. I will let you know when it's fixed and then you shouldn't be needing that extra discount article.

**Comment by Boxedsolutions** [comment]
Should be fixed now.

**Comment by andyjohansson** [comment]
Is this tested @joakim-combain?

**Comment by joakim-combain** [comment]
I checked it and it looks good. You can close this issue.

**Comment by andyjohansson** [comment]
Ok, great
