### ISSUE TITLE
Research how to optimize rounding with the new API

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#28]
We need to make sure that the rounding is set correctly based on the settings of the shop.

**Comment by andyjohansson** [comment]
Any status on this one @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
The amounts between checkout and Billmate are the same. So there is no need for that right now. 

I must find a way to implement it if our shop owners has a module for rounding, a easy fix would be to implement GrandTotal - our calculated total, and use that as a rounding?

**Comment by andyjohansson** [comment]
Could you elaborate on that?

**Comment by Boxedsolutions** [comment]
Lets say a shop owner has a module installed that adds or removes from the GrandTotal to round to nearest unit. The real GrandTotal with VAT is lets say 10.30. And the module rounds to 10.00

We are calculating all items and shippings and discounts and will get 10.30. 

Therefore $grandtotal = $quote->getGrandtotal() Will become 10.00

$rounding = $grandtotal - $ourcalculatedTotal

$rounding = -0.30

I Think it would work as we dont need to bother about how the shop owner rounding module names the total.

**Comment by andyjohansson** [comment]
Sounds like a great idea, do we know any modules that we could test with?

**Comment by Boxedsolutions** [comment]
I will check for one in the weekend ;)

**Comment by andyjohansson** [comment]
Can we test and verify this @Boxedsolutions now? What's the best way to test this?

**Comment by Boxedsolutions** [comment]
I guess its implemented ready. Its never differs between the total to pay in BO and Magento. 

With this approach it doesnt matter if the client adds a rounding module as we round up so the total shown in magento is the same as we get in BO.

Rounding is nice.

**Comment by andyjohansson** [comment]
I will close this one and we can create a new ticket about it if it comes up again.
