### ISSUE TITLE
Compatibility with FireCheckout and get adress

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#29]
* Add compatibility with FireCheckout (include seperate files depending on if FireCheckout is enabled)
* Option to add getadress to the checkout

**Comment by andyjohansson** [comment]
What's the status on this one?

**Comment by Boxedsolutions** [comment]
I need to install FireCheckout to verify. But it looks promising.

**Comment by andyjohansson** [comment]
Ok great, just update us when we are able to test it.

**Comment by Boxedsolutions** [comment]
Splitted up this issue to make it more correct in my development.

**Comment by andyjohansson** [comment]
Can we close this one then?

**Comment by Boxedsolutions** [comment]
Yes This is now in separated Issues
