### ISSUE TITLE
I get no discount counted for SNYGG GRUND TSHIRT KONFIGURERBAR when using card

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#31]
In the invoice I get in BO, there is only 1,63 discount given. Seems like no discount is counted for SNYGG GRUND TSHIRT KONFIGURERBAR. This seems to only happen when using card for some reason. Apilogsid: 1447

**Comment by Boxedsolutions** [comment]
Ahh It might bee my mistake. Did you notice if it says - grön T-shirt after SNYGG GRUND TSHIRT KONFIGURERBAR in the title? 

Will check it out as soon as possible.

**Comment by joakim-combain** [comment]
It says that in the article title in the invoice. Looks good. :)

**Comment by Boxedsolutions** [comment]
Great. I will fix it after lunch if its okay. Now that I know where to change and update all payment methods in the same way.

**Comment by joakim-combain** [comment]
Sounds great!

**Comment by Boxedsolutions** [comment]
Working right now on a solution for different taxes with disount. 

It work if all taxes are 25% right now. But it is still an issue if you add a article with 25% and one with 12%.

**Comment by andyjohansson** [comment]
Ok, and if it is three or four different?

**Comment by Boxedsolutions** [comment]
I will test a new Solution Right now, which I hope to solve this.

The number of different taxes doesnt matter.

**Comment by Boxedsolutions** [comment]
Should be solved now.

**Comment by andyjohansson** [comment]
I will leave this open until tomorow. We will need to check the platform of Billmate and see if we can fix the discount issue there as well.

**Comment by joakim-combain** [comment]
Now, for some reason, you send in 10.25 (which is rounded up for some reason to 10.3) discount for Liten testprodukt åäö but for Snygg grund tshirt Konfigurerbar you send 10.19472361809 (which is rounded up to 10.2). The discount code has a value of 10.2%, both of these products has 25% vat what I can see. For Test produkt you are sending in 20.40265806961 (which is rounded up to 20.4) in discount. The discount amount for test produkt should only be 5.005% (to be precise) and then an additional discount for the cart discount which needs to be sent in as a seperate product. 

So, only Test produkt should have a rebate value for it having a special price when buying two pieces. Then a discount product for the entire cart, thought @andyjohansson would have informed about this yesterday? See invoice number 6414 in Opencart BO account, apilogsid 1611.

I will put on our developer to fix the rounding of the discount percentage in the invoice.

**Comment by Boxedsolutions** [comment]
Should be fixed now invoice id 6415 the amounts seems to bee correct.

**Comment by andyjohansson** [comment]
Will you test and verify @joakim-combain?

**Comment by joakim-combain** [comment]
I've tested and what I can see, it's looking good. So you can close this issue.

**Comment by andyjohansson** [comment]
Ok, great, we are making progress :+1:
