### ISSUE TITLE
Standard transaltion of module titels when activated

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#32]
The standard title of the different modules should be depending on the language the store has when they are activated or installed, depending on easiest implementation.

**Comment by andyjohansson** [comment]
Any status on this one @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
In short no, i think i it would be possible to translate with the csv, but it might introduce som issues.
One possible way is to clear the field and check if the field is empty and use Standards as title Billmate Invoice which is easy to translate.. 

As the code is now: 
public function getTitle(){
        return (Mage::getStoreConfig('payment/billmatecardpay/title') == '') Mage::helper('billmatecardpay')->__('Billmate Cardpay') : Mage::getStoreConfig('payment/billmatecardpay/title'); 
    }
Typ nåt i den stilen borde lösa det :)

**Comment by andyjohansson** [comment]
If we don't declare it in the csv file of the config coulden't we just handle it then if it is empty? And add it depending on the language of the store. How would this function in i multilanguagestore? Is it possible to have multiple textboxes for all the languages? Or how is it handled in Magento?

**Comment by Boxedsolutions** [comment]
Its configured per store :) There is a dropdown in the menu in the left that you may select Store View.

**Comment by andyjohansson** [comment]
Ok, but let's implement it like we both suggested.

**Comment by andyjohansson** [comment]
Can you @Boxedsolutions explain to @joakim-combain how he should test this and verify?

**Comment by Boxedsolutions** [comment]
Just remove the titles in the Configuration for the payment methods. Then it will default to Translation by Csv files.

**Comment by Boxedsolutions** [comment]
Just switch language in System ->  Configuration -> General -> Locale To change language

**Comment by joakim-combain** [comment]
Doesn't seem to work. I've changed it in magento18.boxedtest.se. Am I checking wrong store or something? Couldn't be a browse caching issue?

**Comment by Boxedsolutions** [comment]
Nope. It works but you had to clear all titles for Billmate Payment Methods. 
![verified](https://cloud.githubusercontent.com/assets/8977650/5836932/0e16c8ba-a17b-11e4-8476-950b319a5caf.png)

I did that on 1.8

**Comment by andyjohansson** [comment]
Månad should have a lowercase letter.

**Comment by andyjohansson** [comment]
and "per" is not necessary.

**Comment by joakim-combain** [comment]
Ah, I thought I did that though... It looks good to me, some small issues that Andy noted already. Can't see any major errors. Should the back end also be in english or should our things be in swedish? Like Transaction mode in card (Sale and Authorize only).

**Comment by andyjohansson** [comment]
What do you think @Boxedsolutions? I think that if we change the backend language the translations in the backend are made as well. I know that @Boxedsolutions has been working on this.
If you try to change back to English @joakim-combain, does it look ok then as well?

**Comment by andyjohansson** [comment]
Wait, "Billmate Bankpay" should be "Billmate Bankbetalning"?

**Comment by Boxedsolutions** [comment]
I guess its a human misstake in the Csv files. No big things.

**Comment by andyjohansson** [comment]
Ok, no biggie, just let us know when it's fixed :)

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I removed all titles and now it says nothing in checkout. Am I misunderstanding how this is supposed to work?

![checkout](https://cloud.githubusercontent.com/assets/10434920/6329532/909adc94-bb71-11e4-9d9d-e000e7098997.png)
![configuration system magento admin](https://cloud.githubusercontent.com/assets/10434920/6329543/a6fc14f8-bb71-11e4-98c6-080b90fefe56.png)

**Comment by Boxedsolutions** [comment]
Yes I had to let the translation files take care of the Title field, because of Firecheckout compatibility. It should translate automatically

**Comment by joakim-combain** [comment]
Ok, so what I should test is just that it translates it correctly? We do not have a standard name then, say if the customer accidently removes the title?

**Comment by Boxedsolutions** [comment]
We could add something if the customer removes the title. To make our plugin rocksolid.,

**Comment by andyjohansson** [comment]
Yes we should, we have the same functionality in Prestashop right? Copy the exakt same ones from there then. Otherwise assign me again and I will give you the transaltions @Boxedsolutions.

**Comment by Boxedsolutions** [comment]
In prestashop the titles are translated with the translation tool which is the same as we does in Magento, with that feature that customer can modify the title per store. 

But we might need to secure that the client has a title otherwise its possible to set at default translation. Its firecheckout that picks our titles when choose default payment method.

**Comment by Boxedsolutions** [comment]
Applied the logics to check if the title field is empty to default the translation to the standard titles.

**Comment by joakim-combain** [comment]
There is one small issue. In swedish, if you leave part pay empty it says partpay, should be delbetalning by default if the language is english.

**Comment by Boxedsolutions** [comment]
Can you take a screenshot? I dont really understand what you say. 
If the language is English it must be partpay?

**Comment by joakim-combain** [comment]
If you have swedish language setting in Magento, I think it should currently be in swedish, atleast 1.8. So if you go there it should be saying partpay since I didn't bother putting back the titles.

![magento partpay](https://cloud.githubusercontent.com/assets/10434920/6635315/e7561264-c964-11e4-95be-3096ad24fd3b.png)

**Comment by Boxedsolutions** [comment]
Should be fixed now.

**Comment by andyjohansson** [comment]
/ Mounth should not have a capital "M".
