### ISSUE TITLE
I get different values in checkout and in card payment window.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#33]
To get this issue I use the following in cart:

1 x SNYGG GRUND TSHIRT KONFIGURERBAR
1 x LITEN TESTPRODUKT ÅÄÖ
2 x TEST PRODUKT
Discount code: Test åäö

http://awesomescreenshot.com/0ea47fx46c
http://awesomescreenshot.com/08647fxw5f

**Comment by Boxedsolutions** [comment]
Great, it might be an issue when calculating the discount amount and the discount is multiplied by quantity. 

Will make a fix as soon as possible. 

Its really nice to get this detailed reports.

**Comment by Boxedsolutions** [comment]
Should be fixed now invoice id 6415

**Comment by joakim-combain** [comment]
Great, as I said in the other issue ticket, you shouldn't send in 10.2 for all of them, you should send in a seperate discount product when it's the whole cart. Only if a product has a discount, like a sale, it should have a value in discount, as I understood it. I might be wrong, though. Maybe @andyjohansson can explain how it should be?

**Comment by Boxedsolutions** [comment]
I do a check in the code to se if the article in the cart has a discount and apply the discount percent from magento. 

Hmm. I must figure out how to verify if the discount is on the whole cart. 

So the discount property on the Article element should only be in use if it the discount not applies to the whole cart?

**Comment by joakim-combain** [comment]
That is how I understood it when we talked about it. Perhaps I need to update the spec again to make it clear that the discount for a single product should only work for cases like a sale or something and specify that if it's a cart discount it should be a separate article sent in? Do you feel like the spec is misleading in some way on this topic?

**Comment by Boxedsolutions** [comment]
No its just me I think. 

I must figure out the best way to implement the logic for that. 
I will do a deep dive in Magento CartRule Api and see what i find :)

**Comment by Boxedsolutions** [comment]
If you check under Promotions -> Shopping Cart Price Rule 

And check the tab Actions and field Apply. The selected method is Percent of Product price discount which means a percentual price discount per article. You may also add Conditions to choose which Products that will get a discount with the coupon

There is a alternative for Fixed amount discount which sets a fixed discount per article. Not recommended for use as it will use the total for discount and the taxrates is compounded. I guess this one is if there is a promo for one Product etc.

An other alternative is Fixed amount discount for whole amount cart, which will add a row with the discount amount in the invoice.

**Comment by joakim-combain** [comment]
Ah, ok. So then you are doing correctly. So I should choose the Fixed amount discount for whole cart. Then I think this issue is solved and I'll try with a different discount code. If there are more issues, I'll add new tasks.

**Comment by andyjohansson** [comment]
Great it got sorted out.

**Comment by joakim-combain** [comment]
I now noticed I'm getting different values in checkout and in bank payment window. Can we reopen this issue or should i post a new one?

**Comment by Boxedsolutions** [comment]
Do you have logId? I will fix it directly

**Comment by joakim-combain** [comment]
1656

**Comment by Boxedsolutions** [comment]
Should be fixed, was a typo from my side.

**Comment by joakim-combain** [comment]
Yeah, looks fine now.

**Comment by andyjohansson** [comment]
Ok, I can keep this one closed then?
