### ISSUE TITLE
Add getadress functionality to the module

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#34]
Add getadress functionallity to the standard magento checkout, should be a setting in the invoice and partpayment module. But if one of them have true and the other false, how should the module react?

**Comment by andyjohansson** [comment]
Any news regarding this?

**Comment by Boxedsolutions** [comment]
Like i said for the firecheckout its some considerations that must be taken #49

**Comment by andyjohansson** [comment]
Please test this @joakim-combain. The get adress can be enabled and disabled in the new common module.

**Comment by joakim-combain** [comment]
I've checked this and I tried with all different kinds of formats and it seems to be working good. Closing this issue.
