### ISSUE TITLE
Magento 1.6 - I put an order but the vat rates seems messed up.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#35]
If you check the api log you can see that you have sent in no VAT for Enkel livs moms and 40% for Enkel standard moms.

http://awesomescreenshot.com/08847xolbc

Apilogsid: 1705

**Comment by Boxedsolutions** [comment]
Thats interesting, will check it up if there are some change.

**Comment by joakim-combain** [comment]
I just checked with 1.7 and that one seems to work. Will check if 1.8 has this issue.

**Comment by joakim-combain** [comment]
How is this issue looking? Still an issue with vat being wrong in 1.6.

**Comment by Boxedsolutions** [comment]
Its complicated in 1.6 as all VAT is added to one Article as you will see when you check the order in Magento backend. 

I tried a while yesterday to test different configuration options if it was a configuration thing. The VAT amount is correct, but its not specifies percent per article.

**Comment by andyjohansson** [comment]
It seems like there is no way to resolve this on the 1.6 version then? We should maybe then just add in the readme file for the project a list of known issues and add this one? Or do you have another idea @Boxedsolutions ?

**Comment by Boxedsolutions** [comment]
Not for now :( 

But someday I will get the solution.

**Comment by andyjohansson** [comment]
Ok, assigning myself and adding this as a known issue. After that we will add this one to the back-burner.
