### ISSUE TITLE
Magento 1.6, 1.7, 1.8 - There seems to be an issue with rounding.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#36]
If you compare invoice number 6430 in opencart BO account and order id 100000002 in magento 1.7 store, you'll see a 0.01 difference in total. Check if this is something you can fix. This issue was for 1.6 and 1.7 so assuming this will be in 1.8 as well.

Apilogsid: 1707

**Comment by Boxedsolutions** [comment]
Its now that the rounding feature would be handy. Will implement that today.

**Comment by Boxedsolutions** [comment]
Its now implemented and updated files on Magento Version 1.6, 1.7, 1.8 and 1.9

**Comment by Boxedsolutions** [comment]
The total shows correct on the invoice, but it doesnt show anything on the rounding element in the invoice in BO. 

LogId 1716 Invoice 6434

**Comment by joakim-combain** [comment]
I just confirmed this to be an api bug. I've logged it for Wednesday to be fixed.

**Comment by joakim-combain** [comment]
this is now fixed from our side as well, so we can close this issue.

**Comment by andyjohansson** [comment]
Can you give this a second go @Boxedsolutions before we close it?

**Comment by Boxedsolutions** [comment]
Its implemented correct. Its just to close
