### ISSUE TITLE
Remove all Billmate payment methods for new back-end orders

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#37]

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by andyjohansson** [comment]
Can you verify @joakim-combain ?

**Comment by joakim-combain** [comment]
Can you clarify what the issue is? I don't understand what it is that I should verify.

**Comment by Boxedsolutions** [comment]
If you go in the backend and tries to add a order manually. Our Payment methods shouldnt be visible.

**Comment by andyjohansson** [comment]
We will add them back once we have the support for this.

**Comment by joakim-combain** [comment]
This is fixed.
