### ISSUE TITLE
Create a Common Module for general settings

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#38]
A module only for settings and common stuff for Billmate Payment Methods. 

Will take care of:
 -settings for FireCheckout
 -settings for GetAddress
 -settings for billmate.css

Might take care of: 
 - Credentials?

Add more things if it comes up.

**Comment by andyjohansson** [comment]
We should include credentials in the 2.0 release as well. Could we do an auto import of the credentials if all of them are the same for all the activated payment methods?

**Comment by Boxedsolutions** [comment]
Will check and implement a solution for that.

**Comment by andyjohansson** [comment]
@Boxedsolutions will create a possibility to test this @joakim-combain.

**Comment by andyjohansson** [comment]
@Boxedsolutions will clarify what should be tested here, then assign @joakim-combain for testing.

**Comment by Boxedsolutions** [comment]
![billmatecommon](https://cloud.githubusercontent.com/assets/8977650/6184386/5fa37de8-b361-11e4-914d-60ea74f3812c.png)

Here above are the settings for billmate common module, such as activate our specific files for Firecheckout, Activate getAddress, Activate a custom css. The way to test the css file is to activate and go to checkout and check your console in browser for stylesheets, and verify that the red marked as not found file names billmatestyle-custom.css.

Get Addres active
![getaddressactivefc](https://cloud.githubusercontent.com/assets/8977650/6184447/ff428d1c-b361-11e4-9e46-4fda4eac3eac.png)

Verify that credentials are in the section below. And make sure they kan be verified with the button. 
![creds](https://cloud.githubusercontent.com/assets/8977650/6184455/3083f00a-b362-11e4-835a-615aa5e137c0.png)

**Comment by andyjohansson** [comment]
Isn´t it better to have Get adress on the same row on the checkout?

**Comment by joakim-combain** [comment]
this seems to work. There is room for improvement but that's things we will have to discuss. Should we close this?

**Comment by andyjohansson** [comment]
Yes, closing.
