### ISSUE TITLE
Magento 1.6 - Part pay drop down menu is in swenglish.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#39]
I'm not sure if you have discussed this or how this should be but either it should be entierly in swedish or it should be in english.

**Comment by andyjohansson** [comment]
Do you have a screenshot?

**Comment by joakim-combain** [comment]
https://drive.google.com/file/d/0B8nZhLflMVxNNHJheWk4SFI1QzQ/view?usp=sharing

**Comment by andyjohansson** [comment]
Can you investigate @Boxedsolutions ?

**Comment by Boxedsolutions** [comment]
I work on that. But the plans is in swedish in database. I have to locate the right logId to get the data sent to the Api and the response back. 

It might need some thinking about, a store can sell to Sweden and have the language both in English and Swedish. If the country is "se" and the currency is "SEK" and the language is "en", should the paymentplan description be localized to english? 

One solution would be to wrap the description in translate block, but its no good solution if there are new campaigns the store owner need so edit the translation csv files to localize the new phrases.

**Comment by andyjohansson** [comment]
Yes, it should always be depending on the localization. That's why we should write SEK and not kr.
But we should have standard transalations for type = 1 and nbrofmonths = 3, 6 or 12. That's all the standard stuff.

But @joakim-combain we need to discuss how we should handle the localization on the server side. Since we are sending language we should be able to post back a correct string. Since it's the server and API which are responsible for this.

**Comment by Boxedsolutions** [comment]
Some thing to think about is if we should use Magento Locale From settings. "general/locale/code" For getting response in correct language? 

In that case we need to add a field in the database table for Paymentplans and that is store_id. To allways have localized paymentplans per store(language)?

**Comment by joakim-combain** [comment]
@andyjohansson We can take that discussion with everyone on Thursday and see where we end up.

**Comment by andyjohansson** [comment]
Sure @joakim-combain

**Comment by andyjohansson** [comment]
This weekend we will enable internationalization support for getpaymentplans. So you will receive the correct one if it's available. We are right now discussing how the errors should be handeld such as:
If you submit a language which is not defined, what should the standard response be?

**Comment by Boxedsolutions** [comment]
One solution could bee to default to english if its not handled.

**Comment by andyjohansson** [comment]
I think so as well.

**Comment by andyjohansson** [comment]
Remove the transalation, then assign @joakim-combain to test it.
Update PaymentPlans and do it in the english lanugage and make sure this works. @joakim-combain

**Comment by joakim-combain** [comment]
This is still in swenglish.

![part pay in swenglish](https://cloud.githubusercontent.com/assets/10434920/6329077/8f89eea2-bb6d-11e4-9f7e-d5f8b82c1e4d.png)

**Comment by Boxedsolutions** [comment]
It must have been a cache issue.. I have cleared the magento Cache and now it seems to show correct

**Comment by joakim-combain** [comment]
Hmm, I still have it.... I even cleared my own browser cache.

**Comment by Boxedsolutions** [comment]
![delbetala](https://cloud.githubusercontent.com/assets/8977650/6329427/6cbed790-bb70-11e4-9b0f-afec8df936c9.png)

Seems very strange.

**Comment by joakim-combain** [comment]
Ah. There is the issue. You are checking 1.6 my issue is in 1.8. I should have mentioned that.

**Comment by Boxedsolutions** [comment]
![partpay18](https://cloud.githubusercontent.com/assets/8977650/6368688/4c11f9d0-bcdf-11e4-8f3f-773a76036248.png)
Its the same paymentplans in both firecheckout and standard checkout. I think it could have been a cache issut

**Comment by joakim-combain** [comment]
Now that I change to english it says "3 månaders delbetalning 1374 SEK / Month". There is an issue with translation files I think.

![magento translation needed 2](https://cloud.githubusercontent.com/assets/10434920/6389025/422fd362-bda0-11e4-9c7b-16425639c7f1.png)

**Comment by Boxedsolutions** [comment]
Did you update paymentplans after the language change?


Skickat från min Samsung Mobil.

<div>-------- Originalmeddelande --------</div><div>Från: joakim-combain <notifications@github.com> </div><div>Datum:26-02-2015  10:14  (GMT+01:00) </div><div>Till: Billmate/magento <magento@noreply.github.com> </div><div>Kopia: Jesper Johansson <jesper@boxedlogistics.se> </div><div>Rubrik: Re: [magento] Magento 1.6 - Part pay drop down menu is in swenglish.
  (#39) </div><div>
</div>Now that I change to english it says "3 månaders delbetalning 1374 SEK / Month". There is an issue with translation files I think.

**Comment by joakim-combain** [comment]
I did that now and it still is wrong.

**Comment by Boxedsolutions** [comment]
It was stored a set of pclasses in the store specific settings that was swedish. I removed them now to make it easier for you to test. 

It should work

**Comment by joakim-combain** [comment]
Still having this issue. Now swedish is wrong. But I have seen that it works so I'm assuing I can close it?

**Comment by Boxedsolutions** [comment]
Is it nothing to do for me here? Its important that the user fetches the paymentclasses in the right store context.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
