### ISSUE TITLE
Magento 1.7 - This error message is wrong coded.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#40]
I can't seem to get that error message again though, so might be that you have fixed something.

https://drive.google.com/file/d/0B8nZhLflMVxNWnBlRGdZMk8xMms/view?usp=sharing

**Comment by Boxedsolutions** [comment]
Is it a error still? 

This error message is related to rounding. By coded do you mean encoded? Any LogId i can check? 

I fixed the rounding issue around 12 I think.

**Comment by joakim-combain** [comment]
Here is an api log that should match this issue. apilogsid: 1844

**Comment by Boxedsolutions** [comment]
Looks like the Message is JSON encoded, the question is why its still encoded. As Billmate.php decodes the json. 

One possibility is that message property is json encoded twice, on the Api side?

**Comment by andyjohansson** [comment]
Can you check this with the API team @joakim-combain ?

**Comment by joakim-combain** [comment]
There are two ways to do this.

1. Jesper decodes the UTF8 encoded messages like all others have done

2. We put in billmate.php so it does this automatically. However, this will mess things up for the users that it's currently working for right now.

The idea is that the customer should decode the UTF8 when they make their own plugin. So the store itself decodes the message.

How do you want to do this Mr. @andyjohansson?

**Comment by Boxedsolutions** [comment]
1. Its Mage::throwException( utf8_encode( $result['message'])); that shows that message. The response is JSON_ENCODED. My guess is that message is encoded with JSON twice in some way. 

Will look for a solution. My guess is that json_decode will solve that issue.

**Comment by andyjohansson** [comment]
Jesper, try json_decode and check the results.
But I really think we should do this in billmate.php
Not that many are using that one yet.

**Comment by andyjohansson** [comment]
We will update billmate.php so tit will be handled there. We just need to wait for the update.

**Comment by andyjohansson** [comment]
@joakim-combain when is this update coming to the billmate.php? We decided this yesterday.

**Comment by joakim-combain** [comment]
According to out developer it was done yesterday.

**Comment by andyjohansson** [comment]
Can you fix this @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Sure. Will update it as soon as possible

**Comment by Boxedsolutions** [comment]
It is updated

**Comment by andyjohansson** [comment]
And it works now as it should?

**Comment by Boxedsolutions** [comment]
I dont now the right way to verify, But no strange chars when testing denied personal number.

**Comment by andyjohansson** [comment]
@joakim-combain, can you test?

**Comment by joakim-combain** [comment]
I can't really test it unless @Boxedsolutions breaks the plugin on purpose to generate the error message. This error message is that our calculated total does not match the total that you have provided. So the only way to really test it is to send in a value that is wrong according to our calculations.

**Comment by andyjohansson** [comment]
Ok, we close it then. If it pops up again, we have to take another look at it.
