### ISSUE TITLE
Magento 1.7 - Discount is different in store and in invoice.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#41]
There seems to be an issue here with this discount.

You are sending in -800 in discount. -800 * 1.25 = -1000. The discount should be 9.99 and the rounding should be one öre more I think.

http://awesomescreenshot.com/05448aao35

{"quantity":1,"artnr":"discount","title":"Discount","aprice":-800,"taxrate":25,"discount":0,"withouttax":-800}

https://billmate.se/invoice/20150120142308927554be377331bf4

However, the sums are correct, probably because you are sending in a rounding value that corrects the grand total.

**Comment by Boxedsolutions** [comment]
Its rounding 9.99 to 10.00 
Will fix this issue later and verify the function and update here. 

Yes I find the rounding value very useful :) It will make the total to pay allways the same as in Magento.

**Comment by joakim-combain** [comment]
But you are sending in 800. This is 1000 incl. 25% vat.

Yep, that's the idea :smile:

**Comment by Boxedsolutions** [comment]
Should bee solved now. 
"quantity": 1, "artnr": "discount", "title": "Discount", "aprice": -799, "taxrate": 25, "discount": 0, "withouttax": -799 }

**Comment by joakim-combain** [comment]
Yep, this is fixed. You can close this issue.
