### ISSUE TITLE
Validate that login credentials work

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#44]

**Comment by andyjohansson** [comment]
Do what via http://billmate.se/api-integration/getpaymentplans/

**Comment by Boxedsolutions** [comment]
The question is if we could use javascript Alert to notify the user if the credentials is correct or not?

**Comment by joakim-combain** [comment]
What login credentials is this?

**Comment by Boxedsolutions** [comment]
![credentials](https://cloud.githubusercontent.com/assets/8977650/6329140/091a1a08-bb6e-11e4-8b31-bf1daf78fc54.png)
Here you find the settings for them

**Comment by joakim-combain** [comment]
Ok, where are the login credentials? Are you talking about the keys? Or the activate invoice in BO setting? I'm confused about login credentials since the keys are not login credentials...

**Comment by andyjohansson** [comment]
Nothing more needs to be done here, right?

**Comment by joakim-combain** [comment]
This should be working fine. Closing this issue.
