### ISSUE TITLE
Check if Pclasses Exists when showing Part payment in frontend

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#45]
Check if Pclasses Exists when showing Part payment in frontend

**Comment by Boxedsolutions** [comment]
The logic is now to first Check store specific paymentplans. If it doesnt return any results it defaults to default store. If it either doenst have any results it wont show partpayment alternative

**Comment by joakim-combain** [comment]
I tried this but I got 3 paymentplans but I only had one specific paymentplan.

I used these keys (it's a test account)

9495 828885158288

I got 3 months and 6 months and then the one I added as specific. Should it be like this or it is a bug?

**Comment by Boxedsolutions** [comment]
I didnt found a log with the credentials above.

**Comment by joakim-combain** [comment]
Can you put in the Credentials and check it? I'm not sure if it's an issue or not.

**Comment by Boxedsolutions** [comment]
![pclasses](https://cloud.githubusercontent.com/assets/8977650/6330042/7cbb9958-bb75-11e4-9fd3-5e29a04bb295.png)

It is what i got with this credentials. Will check for a logId

**Comment by joakim-combain** [comment]
Hmm, seems like we are returning this. So it's actually correct on your side...

**Comment by joakim-combain** [comment]
Aha, it could be because we demand that there is a 3 and a 6 months choices. I only put a 12 month option as store specific. @andyjohansson should we do it like this or just keep it to the registered pclasses for the store?

**Comment by andyjohansson** [comment]
Let´s just return the once that are registered to that client @joakim-combain. Will you make sure that we get the updates on the API side for this?

**Comment by joakim-combain** [comment]
This is registered for today on our developer to fix.
