### ISSUE TITLE
Create invoice inside Magento

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#46]

**Comment by andyjohansson** [comment]
Could you clarify this @Boxedsolutions and then assign to @joakim-combain?

**Comment by Boxedsolutions** [comment]
If you go to the order and click on the button up to the right "Invoice" the Invoice should be activated in BO if the setting is activated in Billmate Common module. 

When you have activated the invoice, you can test to credit the invoice by clicking on the left side "invoice" tab and select the invoice and click on the button up to the right "creditmemo" And create a credit memo, then should the invoice be credited in BO. Make sure you click on refund, not refund offline.

**Comment by joakim-combain** [comment]
Hmm, I tried crediting the invoice I activated but it doesn't seem to work.

Order number is 100000018
Invoice number is 7063

Can't see that I did something wrong.

**Comment by Boxedsolutions** [comment]
Its verified its something that makes it strange,

**Comment by joakim-combain** [comment]
What is verified?

**Comment by Boxedsolutions** [comment]
It is something that makes the error in older versions than 1.9. Will check it. 

I have tested it on magento-api-2-0.boxedtest.se and there it seemed to work

**Comment by joakim-combain** [comment]
Ah ok.

**Comment by Boxedsolutions** [comment]
Changed the logics so it should work to activate Invoice now.

**Comment by joakim-combain** [comment]
I can't get our payment methods when creating an order in magento.

**Comment by Boxedsolutions** [comment]
You cant place order in backend. It is some logics both in the api and in our module that needs to be in place


Skickat från min Samsung Mobil.

<div>-------- Originalmeddelande --------</div><div>Från: joakim-combain <notifications@github.com> </div><div>Datum:26-02-2015  10:04  (GMT+01:00) </div><div>Till: Billmate/magento <magento@noreply.github.com> </div><div>Kopia: Jesper Johansson <jesper@boxedlogistics.se> </div><div>Rubrik: Re: [magento] Create invoice inside Magento (#46) </div><div>
</div>I can't get our payment methods when creating an order in magento.

**Comment by Boxedsolutions** [comment]
This feature is when create an invoice in the Sales Order invoice which activates the invoice in BO. 

Its important to verify that amounts is correct when using billmate invoice.

**Comment by Boxedsolutions** [comment]
This References #59 So when #59 is Ready I quess its ready here also.
