### ISSUE TITLE
Compatibility with Firecheckout

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#48]
Split from #29 To make it better for my work with the module.

**Comment by Boxedsolutions** [comment]
A little enchancement. Shop owner is not in need to modify Firecheckout Core template files any more. The field is prepended with Javascript. To make it easier for the shopowner.

**Comment by andyjohansson** [comment]
Super! Any notes about this? In what commit is it?

**Comment by Boxedsolutions** [comment]
Something to consider is if we maybe should have different css files for Firecheckout or Standard?

**Comment by andyjohansson** [comment]
If you think so then I think we should. If Firecheckout is enabled we could include another css file?
Or if we make the css file as a php file and use an if statment inside the php-css file. I've done that before...

**Comment by Boxedsolutions** [comment]
No need for php file. Magento has a nice ifconfig when adding blocks in layoutfile :)

**Comment by andyjohansson** [comment]
Good one! Bet let´s keep in in mind for other platforms.

**Comment by Boxedsolutions** [comment]
Seems like it working

**Comment by joakim-combain** [comment]
I can't get this to work on any of the stores. Am I doing something wrong?

**Comment by Boxedsolutions** [comment]
Its just for 1.8 and newer. You had only missed to Activate Firecheckout itselfs.

**Comment by andyjohansson** [comment]
Can't we have a version control check on that setting?

**Comment by Boxedsolutions** [comment]
It should work on later also, No problem. Its just that i have just installed it on 1.8 and newer.

**Comment by andyjohansson** [comment]
But the setting should not be there if FireCheckout is not installed? We maybe should have a dropdown instead that you can choose the checkout that is being used right now? Or can we detect that somehow?

**Comment by Boxedsolutions** [comment]
I think we could use magento Depends in config. I will se what happens if we are just checking against if Firecheckout is active.

It would be a little easier for the client?

**Comment by Boxedsolutions** [comment]
I have removed our setting for Firecheckout active and depend on Firecheckouts own enabled status. I think it will be easier for our clients

**Comment by joakim-combain** [comment]
Great! Closing this issue.
