### ISSUE TITLE
Get address for FireCheckout

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#49]
split from #29 

Implement getAddress functionality and field in FireCheckout

**Comment by Boxedsolutions** [comment]
Some consideration on how to show address might need to be taken

**Comment by joakim-combain** [comment]
There seems to be some issues with getaddress in FireCheckout. I have managed to put these issues in various other issues.

One issue is that you are not sending paymentplanid for part payment.

**Comment by Boxedsolutions** [comment]
do you have any logId?

**Comment by joakim-combain** [comment]
4760

**Comment by Boxedsolutions** [comment]
{ "PaymentData": { "method": 4, "currency": "SEK", "paymentplanid": "55", "country": "SE", "orderid": "1424774933", "autoactivate": 0, "language": "sv" }

I quess the paymentplan is on the BillmateId 9xxx That you had to get special paymentplan yesterday.

**Comment by joakim-combain** [comment]
Aha, but I have changed to the standard pclasses. So that one shouldn't even be active...

**Comment by joakim-combain** [comment]
Also the last time i tested i used 3 months which should be paymentplanid 1.

**Comment by Boxedsolutions** [comment]
For some reason it was some paymentplans saved on Storeconfig as the module prioritize the store specific paymentplans first to make it possible to have different paymentplans per store. 

I tested now to checkout with partpayment and it seems to work now.

**Comment by joakim-combain** [comment]
Ok that part is fixed.

One thing I don't understand is why we demand a registered user who has a registered address to give person number again in the payment method. Is the person number not saved in the address or something?

**Comment by Boxedsolutions** [comment]
Its a juridic aspect of saving person number. Its better that customer verifies the order with the personnumber which prevent someone to get into another ones account.

**Comment by joakim-combain** [comment]
Ok.

**Comment by joakim-combain** [comment]
Is there anything else that needs to be fixed before I do my standard testing on firecheckout?

**Comment by Boxedsolutions** [comment]
Not what I can see right now. Should bee working

**Comment by joakim-combain** [comment]
The address popup is still wrong encoded. Is this your issue or api issue? I think we looked at it the last time Andreas was at our office. I think our developer said that it's on your side.

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by joakim-combain** [comment]
Fixed. Closing this issue.
