### ISSUE TITLE
Add function to manually fetch new PClasses

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#5]
Add a button or a way to manually fetch the new PClasses.

**Comment by Boxedsolutions** [comment]
Not implemented. 
It updates paymentplans when payment methods config is saved.

**Comment by andyjohansson** [comment]
I will move this to the 2.1 release, but it needs to be implemented. It's a nice function when we manually update the PClasses and they want the data directly. It's easier to understand with a button that does the job :)

**Comment by andyjohansson** [comment]
Please test this @joakim-combain.

**Comment by joakim-combain** [comment]
Seems like I can't fetch any pclasses in any way, pressing the button and just saving doesn't do it. I get message that it has updated it but it seems like we don't fetch them in the first place for some reason.

**Comment by Boxedsolutions** [comment]
Try update the page. Its loading via Ajax. 

I should fix so the plans show upp when loaded.

**Comment by Boxedsolutions** [comment]
Added a fix so it should update the table.

**Comment by joakim-combain** [comment]
There seems to be an issue with pclasses. Sometimes they just seem to disappear. I just make changes in other plugin settings and I also changed store language to swedish and it disappeared. It appears again if I go to payment method settings and refresh. Can we fix this somehow so this won't happen for customers? Part payment dissappears as payment option when this happens.

**Comment by Boxedsolutions** [comment]
In which store?

**Comment by joakim-combain** [comment]
I'm testing 1.6 right now. Not sure if it's in the other stores.

**Comment by Boxedsolutions** [comment]
will check it

**Comment by Boxedsolutions** [comment]
Should work now.

**Comment by joakim-combain** [comment]
Now I changed country restrictions and it was cleaned out. Now I have to click the button to fetch them again...

**Comment by Boxedsolutions** [comment]
Thats strange. I will check what causes that.

**Comment by Boxedsolutions** [comment]
It was some old script that run and deleted the paymentplans. It should work now

**Comment by joakim-combain** [comment]
Hmm, seems to work now. I'll close this issue for now and reopen it if I encounter it again.
