### ISSUE TITLE
Be able to credit an order / invoice from within Magento

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#50]

**Comment by Boxedsolutions** [comment]
Should we start with full credit? And full Capture payment? Also when customer makes the invoice in Magento should it capture the whole amount?

**Comment by andyjohansson** [comment]
Will discuss this on Monday together with developers.

**Comment by andyjohansson** [comment]
This is already implemented, right @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Yes its implemented. Just need to verify #59 So that amounts is working correctly. I have tested BillmateInvoice in magento 1.8 and 1.9 and it works there so I think it should work with the rest

**Comment by Boxedsolutions** [comment]
If also #52 is approved I guess this one should be closed
