### ISSUE TITLE
I get "Server unavailable"-page when trying to access payment method settings in all stores.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#54]

**Comment by joakim-combain** [comment]
![http error](https://cloud.githubusercontent.com/assets/10434920/6208707/247e2016-b5bd-11e4-9170-7062650d262b.png)

**Comment by Boxedsolutions** [comment]
Cant reproduce in any store. Which steps are taken?

**Comment by joakim-combain** [comment]
Hmm, seems like it was cached even in my incognito window.... Strange... Works now after cleaning it out. Closing this issue.
