### ISSUE TITLE
å ä ö is missing in this message.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#56]
![wrong encoding message](https://cloud.githubusercontent.com/assets/10434920/6211528/34c16d34-b5db-11e4-8d8e-75fe89190d5e.png)

I user person number 550505055.

**Comment by Boxedsolutions** [comment]
Will check it.

**Comment by andyjohansson** [comment]
Can @joakim-combain test this again @Boxedsolutions. If so, please assign this issue to him.

**Comment by Boxedsolutions** [comment]
Should be solved

**Comment by joakim-combain** [comment]
Fixed.
