### ISSUE TITLE
AutoActivate doesn't work in 1.6 atleast.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#57]
Invoice number 7000

apilogsid 4021

If you check the apilogs it looks like you are not sending autoactivate as 1, that's the issue.

**Comment by Boxedsolutions** [comment]
Its not autoActivate like that. Its when you are using Magentos Invoice Functions. But there are some Api-bugs that makes it a little complicated now. 

I will give you more info about how to test and verify that when I got the solution with the Api

**Comment by joakim-combain** [comment]
Ah, ok.

**Comment by andyjohansson** [comment]
Status on this one?

**Comment by Boxedsolutions** [comment]
Belongs to #46  I guess

**Comment by joakim-combain** [comment]
This is not working. When I try to Invoice in magento platform it gives an error that the amounts are not matching.

Check order number: 100000047 and invoice number in bo: 7167

**Comment by Boxedsolutions** [comment]
Is it Billmate Invoice? It should work with the other methods. Working on a way to solve this. As stated in #59

**Comment by Boxedsolutions** [comment]
Should work now. Just create new orders with billmateinvoice as the logics are changed.
