### ISSUE TITLE
I activated GetAddress in common functions and it does the same thing in both modes.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#58]
As I understood it, the popup should only come if you use getaddress and then change something and try to continue. Right now the popup comes up all the time. This has only been tested in 1.6.

**Comment by Boxedsolutions** [comment]
It might be some funny misstake there. Will check it. 
Can you verify that the popup doesnt come up if you not use get address and types correct address? Otherwise it is some bug in that part.

**Comment by joakim-combain** [comment]
Seems like the popup comes up even though I have correct address. I also noticed that I probably misunderstood the functionality. I found a "Personal number" field in where I put in my customer information. I thought it was the payment method Personal number field it was using. So I think GetAddress works.

**Comment by Boxedsolutions** [comment]
Is it anything for Me to do here?

**Comment by joakim-combain** [comment]
No. this seems to be working correctly. Closing it.
