### ISSUE TITLE
Check amounts when activate invoice.

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#59]

**Comment by Boxedsolutions** [comment]
Its now implemented.

**Comment by joakim-combain** [comment]
I tried to activate an invoice through magento backend, but I got an error message that the amounts don't match but they do.

**Comment by Boxedsolutions** [comment]
Any screenshots or orderId that makes it easier for me to check it.

**Comment by Boxedsolutions** [comment]
I found the thing that makes the trouble now. Will check for a solution. It is that Magento doesnt add up the taxes on the InvoiceFee to the amount to invoice.

**Comment by Boxedsolutions** [comment]
It is strange as it works in 1.9.1 aka http://magento-api-2-0.boxedtest.se. I have to think over the implementation to see whats the best way to do it, if we might need to add a field to store the invoiceTax on the quote/order/invoice/creditmemo tables or if we store it in the payment table additional info

**Comment by Boxedsolutions** [comment]
Should work now. Just create new orders with billmateinvoice as the logics are changed.

**Comment by joakim-combain** [comment]
Doesn't seem to work. I just tried to activate the invoice by pressing Invoice button in the order and then confirm it but says that the amounts are not matching.

![amounts not matching](https://cloud.githubusercontent.com/assets/10434920/6557610/93fbf872-c676-11e4-9bbe-fbfaade32276.png)

Order number: 100000054
Invoice number: 7182
Apilogsid: 7647

**Comment by Boxedsolutions** [comment]
Is it a new order?

**Comment by Boxedsolutions** [comment]
Is it Magento18?

**Comment by joakim-combain** [comment]
Yes

**Comment by Boxedsolutions** [comment]
Should be fix due to different calculations in 1.9 and 1.8 and earlier
