### ISSUE TITLE
Automatically update PClasses

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#6]
Write a function that automatically updates all the PClasses, once a week.

**Comment by Boxedsolutions** [comment]
It is implemented, as if paymentplans is older than a week its automatically fetches new ones.

**Comment by andyjohansson** [comment]
Great, can you verify this @joakim-combain?

**Comment by andyjohansson** [comment]
Have you tested this yet @joakim-combain ?

**Comment by joakim-combain** [comment]
Fixed. You can close it.
