### ISSUE TITLE
Clicking the link for payment terms for invoice and part pay unchecks the e-mail box.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#60]
This is happening in 1.8 and with standard checkout, as far as I know.

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
I tested on 1.6 now and in the standard checkout I can't get terms for invoice and part pay.

**Comment by Boxedsolutions** [comment]
Should work now. Made a little change

**Comment by joakim-combain** [comment]
Fixed
