### ISSUE TITLE
We need to change the text for e-mail check box.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#61]
We need to change this text:

"Min e-postadress Joakim@efinance.se är korrekt och kan användas för fakturering. Och jag bekräftar även Köpvillkor"

You can't start a sentence with Och. The text should be something like:

"Min e-postadress Joakim@efinance.se är korrekt och kan användas för fakturering. Jag bekräftar även Köpvillkor"

Or

"Min e-postadress Joakim@efinance.se är korrekt och kan användas för fakturering, och jag bekräftar även Köpvillkor"

**Comment by andyjohansson** [comment]
"Min e-postadress, Joakim@efinance.se, är korrekt och får användas för fakturering. Jag bekräftar även köpvillkoren"

**Comment by Boxedsolutions** [comment]
Should be fixed

**Comment by joakim-combain** [comment]
"Min e-postadress joakim@combain.com är korrekt och får användas för fakturering. Jag bekräftar även Köpvillkoren"

Should be

"Min e-postadress, joakim@combain.com, är korrekt och får användas för fakturering. Jag bekräftar även Köpvillkoren" The email should be in comas.

**Comment by Boxedsolutions** [comment]
Should be solved now

**Comment by joakim-combain** [comment]
Unless @andyjohansson has changed his mind without me knowing it, this is still wrong.

It should be "Min e-postadress, Joakim@efinance.se, är korrekt och får användas för fakturering. Jag bekräftar även Köpvillkoren".

**Comment by Boxedsolutions** [comment]
I added a comma sign after email if it was that error? Otherwise I dont see whats wrong

**Comment by joakim-combain** [comment]
According to what Andreas said, there should be another comma after the email. Today you only have one comma in front of the email address. It's also missing last punctuation after Terms of invoice.

Today is: "My email, Joakim@efinance.se is accurate and can be used for billing. I confirm the Terms of invoice"

It should be: "My email, Joakim@efinance.se, is accurate and can be used for billing. I confirm the Terms of invoice."

**Comment by Boxedsolutions** [comment]
Great now i see it :+1: Will fix as soon as possible.

**Comment by Boxedsolutions** [comment]
Like this? 
"Min e-postadress, jesper@boxedlogistics.se, är korrekt och får användas för fakturering. Jag bekräftar även Köpvillkoren."

**Comment by joakim-combain** [comment]
![thumbs-up](https://cloud.githubusercontent.com/assets/10434920/6391602/439b824c-bdb8-11e4-9665-4250a11a2fb8.jpg)

**Comment by joakim-combain** [comment]
The only thing left is to do the same for english. :)

**Comment by Boxedsolutions** [comment]
Should work nice even with firecheckout now.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
