### ISSUE TITLE
In 1.8 I can't checkout with invoice or part pay. It says Missing person number.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#62]
![magento missing personal number](https://cloud.githubusercontent.com/assets/10434920/6327084/7130cee0-bb58-11e4-8811-a9184f3921be.png)

**Comment by Boxedsolutions** [comment]
which version?

**Comment by joakim-combain** [comment]
Magento 1.8 Plugin 2.0

**Comment by Boxedsolutions** [comment]
![firecheckout](https://cloud.githubusercontent.com/assets/8977650/6327161/1029c02e-bb59-11e4-956d-afdb04daa644.png)
Firecheckout setting was active. I have turned it off. Now it Works. But will check for a better solution.

**Comment by joakim-combain** [comment]
Ok great. I'll keep this issue opened and you can let me know when you have found a new solution and then we close it?

**Comment by Boxedsolutions** [comment]
Changed the logics to autoactivate the firecheckout specific settings when firecheckout is active by their module

**Comment by joakim-combain** [comment]
Ok. Closing this issue.
