### ISSUE TITLE
I can't accept the address popup when using Part pay.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#63]
When I press to confirm the address change, nothing happens. If I press cancel it cancels the popup window like it should. This is in 1.8, at least.

This is what I get in console:

![part pay popup issue](https://cloud.githubusercontent.com/assets/10434920/6328265/ef6046ee-bb65-11e4-84ca-b461834d55bf.png)

**Comment by Boxedsolutions** [comment]
Can you try again.

**Comment by joakim-combain** [comment]
This is fixed. Closing the issue.
