### ISSUE TITLE
1.8 - Seems like firecheckout doesn't work with autofill of person information

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#64]
I put in my person number and nothing happened when I pressed tab and there doesn't seem to be any button to fetch the address. Am I doing something wrong or is there a bug here?

![fire checkout](https://cloud.githubusercontent.com/assets/10434920/6345353/873c44fa-bc05-11e4-9e58-2901f1815711.png)

**Comment by Boxedsolutions** [comment]
![getaddress](https://cloud.githubusercontent.com/assets/8977650/6345392/e983b760-bc05-11e4-8861-ab366eb3bd32.png)

I changed the setting to Yes. Please try again.

**Comment by joakim-combain** [comment]
Ahaa... I thought that setting was only for if you don't have firecheckout activated. Must have misunderstood it. Works now. Closing this issue.
