### ISSUE TITLE
When using get address, is it possible to set country to Sweden by default?

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#65]
Only people with a swedish person number will be able to use this function anyway, so when someone presses Get Address, can we set country to Sweden?

**Comment by Boxedsolutions** [comment]
Will add so that country also is returned seems like a miss from my side :(

**Comment by Boxedsolutions** [comment]
I think a solution would be to get the country from getAddress function in the Api to make it future proof

**Comment by Boxedsolutions** [comment]
Should be fixed now. When clicking getAddress it takes the country from the api and select correct country

**Comment by joakim-combain** [comment]
I have an issue now. The plugin is letting my orders through with my person number. I should be blocked in our system from doing this. I also noticed that if I use getAddress on 5501011018, country is removed.

Apilogsid: 5844

**Comment by Boxedsolutions** [comment]
The log shows status Ok by your person number. It should now select the correct country..

**Comment by Boxedsolutions** [comment]
Should be fixed I think.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
