### ISSUE TITLE
1.8 - I seem to have issues with getting shipping methods when adding a new address.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#66]
Even after I choose country, the alternatives won't show up. Am I doing something wrong?

![fire checkout2](https://cloud.githubusercontent.com/assets/10434920/6345678/b22db7ae-bc08-11e4-927c-eca64dc339bd.png)

**Comment by Boxedsolutions** [comment]
I will try to update firecheckout to the latest. It gets no ajax request.

**Comment by Boxedsolutions** [comment]
For some reason it needs to uncheck "Frakta till samma address" and select country to show shipping methods. 

I will take it up with Templates Master.

**Comment by joakim-combain** [comment]
Ok. I found something else now. If I choose the address I have saved and try to checkout it gives "Missing person number" message. This is probably due to GetAddress being activated and not filled, or am I wrong?

**Comment by Boxedsolutions** [comment]
Should work now

**Comment by joakim-combain** [comment]
I got this now. It's missing åäö and it seems like the address wasn't changed.

![error code 2402](https://cloud.githubusercontent.com/assets/10434920/6346302/197a1460-bc0f-11e4-881f-2dad0437d5dd.png)

**Comment by Boxedsolutions** [comment]
I think it is not possible to update the address selected if you're not using new address with the code as it is now.
In what reason does a customer need that?

**Comment by Boxedsolutions** [comment]
![nekat](https://cloud.githubusercontent.com/assets/8977650/6346483/8fa80222-bc10-11e4-8f6e-065a3b5099b0.png)

I got this when add new address with denied number

**Comment by joakim-combain** [comment]
They ar probably not gonna need it. I'll test it from scratch instead, with creating a new customer etc.

**Comment by Boxedsolutions** [comment]
Is it anything I need to update here?

**Comment by joakim-combain** [comment]
Has this been solved from third-party? Is this something we even care about? This issue won't occur that often anyway?

**Comment by Boxedsolutions** [comment]
I think we made a fix for this when we changed the way the personal number was injected

**Comment by joakim-combain** [comment]
Just checked it and it works. Closing this issue.
