### ISSUE TITLE
I'm getting a wrong encoded address popup.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#67]
I tested in 1.8 and created a new customer. When I use GetAddress, it gets wrong encoded.

![fire checkout2](https://cloud.githubusercontent.com/assets/10434920/6347711/59feec9e-bc1a-11e4-978c-897199fe0322.png)

**Comment by Boxedsolutions** [comment]
$addr[$key] = utf8_encode($col); This is the code i am using to encode to utf8. 

As you see it doesnt work with utf8_encode.. Is it some Api-related?

**Comment by joakim-combain** [comment]
I also got "Ogiltigt paymentplanid" when trying to pay with part pay.

**Comment by Boxedsolutions** [comment]
I was testing the activateInvoice before with opencart account. Its two ways to solve it. Either update paymentplans or change the credentials to the one with special paymentplan

**Comment by joakim-combain** [comment]
I also noticed that if you do not have an account and come to the checkout, you only have to give the person number in the customer information part. But when you have a registered account, you have to enter person number in the payment method as well.

**Comment by Boxedsolutions** [comment]
Should work

**Comment by joakim-combain** [comment]
This issue is solved. Closing it.
