### ISSUE TITLE
I was trying to put an order with invoice but it returns error message that what you are providing is not matching with expected.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#68]
I am using a registered customer.

It seems like it does the address check just to confirm that the given address is correct and is not overwriting if it's wrong.

Not sure how big of an issue this is since people will not give a different person number the next time they buy something. The issue will be if the customer has had an address change, but then the customer most likely will change the address to a correct one before checking out.

**Comment by Boxedsolutions** [comment]
We let @andyjohansson  Think about it-

**Comment by andyjohansson** [comment]
Yes, I agree with @joakim-combain. But can't we ask if they would like to update the adress @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Will check for a solution

**Comment by Boxedsolutions** [comment]
Should work now.
