### ISSUE TITLE
Change the way subtotal is fetched in Payment modules

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#7]
The change from
$data =  $quote->getTotals();
$total = $data['subtotal'];

to 
$total = $quote->getSubtotal();

**Comment by andyjohansson** [comment]
Is this fixed @Boxedsolutions ?

**Comment by Boxedsolutions** [comment]
Yes it is. In commit d00642d68f35e976f85da8914bdcbc4622a88457

**Comment by andyjohansson** [comment]
Is there any way to test and verify this, otherwise I will close this one.

**Comment by Boxedsolutions** [comment]
I cant see how it could bee verified. Its no differences in frontend, just how other modules, for example other checkouts handle the totals.

**Comment by andyjohansson** [comment]
Ok, then I will close this one.
