### ISSUE TITLE
I'm not able to put an order in 1.8 with test person number

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#70]
I'm getting error message saying that we are sending Sverige but expected was Sweden. Can we do a work around here and put if 5501011018 is used we send Sweden instead of Sverige?

Apilogsid: 6518

**Comment by Boxedsolutions** [comment]
Could you please try again.Think I have fixed it.

**Comment by joakim-combain** [comment]
This is fixed. Closing it.
