### ISSUE TITLE
Discount code teståäö is sent in wrong. It should be devided into two products if there is different vat rates on the products.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#71]

**Comment by Boxedsolutions** [comment]
Discount Code teståäö isnt that procentual? Just implemented a fix for fixed value discount so that we split the discount depending on vatrate for the products in cart.

**Comment by andyjohansson** [comment]
So @joakim-combain can test this @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Yes, I just need to add te tax Rates to the title in the invoice. Will do it in a couple of minutes, and when its ready I will assign Joakim

**Comment by Boxedsolutions** [comment]
Should be fixed in commit 042fb6b
