### ISSUE TITLE
You shouldn't be able to Invoice and paid card order.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#73]
In Magento 1.8 I was able to press Invoice on an paid test card order. Try to fix so this won't be possible. It doesn't really do any harm in test mode, but have no idea what it will do with a live card order.

**Comment by Boxedsolutions** [comment]
The only thing that happens when the order is not in created state is that the invoice creates in Magento to keep track on sales. 

If i Disable that part magento Sales order tracking would be useless.

**Comment by joakim-combain** [comment]
Ok. Closing the issue.
