### ISSUE TITLE
I tried crediting a card order from magento, but nothing happend in Billmate Online.

### ISSUE THREAD

**Issue by joakim-combain** [Billmate/magento#74]
I tried with both Refund and Refund offline.

Order number: 100000068
Invoice number: 433595

**Comment by Boxedsolutions** [comment]
Did you click on the invoice first?

**Comment by Boxedsolutions** [comment]
Should work now. I corrected a logic misstake.

**Comment by joakim-combain** [comment]
This issue is fixed. Closing it.
