### ISSUE TITLE
Keep cart contents on cancel payment

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#8]
A fix for keeping shopping cart after canceled or a payment error, 

Need to clear $quote->reservedOrderId or else Magento will complain about order already exists

**Comment by Boxedsolutions** [comment]
Its implemented

**Comment by andyjohansson** [comment]
Can you verify this @joakim-combain? On all of the payment types.

**Comment by andyjohansson** [comment]
Have you tested this yet @joakim-combain ?

**Comment by joakim-combain** [comment]
This is fixed. You can close this issue.
