### ISSUE TITLE
Part pay from this amount on product pages

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#88]
Just like in WooCommerce

**Comment by andyjohansson** [comment]
Pushing to future release.

**Comment by Boxedsolutions** [comment]
Is it okay to let customer place it wherever they want? 

Example echo $this->getChildHtml('billmate_pay_from'); 

This way customer could put it where they wanted and not be forced to put it where we add it? It will also affect the styling regardless so its impossible to set css/classes for every theme that exists.

**Comment by andyjohansson** [comment]
Sounds like a good plan @Boxedsolutions. Please implement and document the support for it.

**Comment by Boxedsolutions** [comment]
for use in catalog/product/view.html
<?php echo $this->getChildHtml('billmate_payfrom'); ?>

Let the developer choose where to place it and how to style it.
