### ISSUE TITLE
Review the getadress function

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#96]
* Javascript error in billmatepopup
* Error code should be below the get adress button
* No error code if person number is invalid if language is swedish

![skarmavbild 2015-04-23 kl 15 50 03](https://cloud.githubusercontent.com/assets/4968755/7298514/70fe6850-e9d0-11e4-93ae-c5e6ac85ec06.png)

**Comment by andyjohansson** [comment]
Also is the error message added multiple times.

**Comment by andyjohansson** [comment]
When you make a new request, clear the error message.

**Comment by Boxedsolutions** [comment]
Seems to work now

**Comment by andyjohansson** [comment]
Still multiple error codes.
![skarmavbild 2015-04-28 kl 14 19 30](https://cloud.githubusercontent.com/assets/4968755/7369337/9d04b38e-edb1-11e4-83d6-b990a83b58e4.png)

**Comment by Boxedsolutions** [comment]
Fixed now

**Comment by andyjohansson** [comment]
We today show an alert if person number is missing. Shouldn't this be done according to standard?
![skarmavbild 2015-04-28 kl 14 35 56](https://cloud.githubusercontent.com/assets/4968755/7369686/20167e86-edb4-11e4-9fc2-697f2d9af06b.png)
![skarmavbild 2015-04-28 kl 14 36 58](https://cloud.githubusercontent.com/assets/4968755/7369687/209b6c4a-edb4-11e4-8451-8aa1d6ef54a6.png)

**Comment by Boxedsolutions** [comment]
Its a validation that lies in our payment module. Its not that easy to get this in the standard way as we throw an exception and magento makes the alerts

**Comment by andyjohansson** [comment]
But can't we from the JS add the classes and so on?

**Comment by andyjohansson** [comment]
Also add correct validation classes to the input box of the person number.
