### ISSUE TITLE
Verify credentials that it works in storeview

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#97]
In some situations that I have encountered the Credentials will be missing if it only set under Default.

I have to find a way around this.

**Comment by andyjohansson** [comment]
No update on this one?

**Comment by Boxedsolutions** [comment]
Not for now

**Comment by andyjohansson** [comment]
We might have to push this to 2.1 then.

**Comment by Boxedsolutions** [comment]
Yes I think it will be a good solution.

**Comment by andyjohansson** [comment]
Will do that then, could you write something for me to put in "Known issues"?

**Comment by andyjohansson** [comment]
@Boxedsolutions?

**Comment by andyjohansson** [comment]
Pushing to 2.1 now and added to the list of known issues.

**Comment by andyjohansson** [comment]
Pushing to future release.
