### ISSUE TITLE
Redesign Billmatepopup for the different Checkouts

### ISSUE THREAD

**Issue by Boxedsolutions** [Billmate/magento#99]
My Ideas are one common Javascript class, that manage all common stuff and one for each checkout to make it easier to implement custom logics

**Comment by andyjohansson** [comment]
Sound like a great plan for 2,1!

**Comment by andyjohansson** [comment]
Pushing to future release.

**Comment by andyjohansson** [comment]
Is this still needed @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Its already fixed i think
